package Atm;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author USER
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.JOptionPane;
public class ATMS extends javax.swing.JFrame implements ActionListener{
 public int withdrawamount;
public  int balance1, balance2;
    private Object jtxtDisplay;

    /**
     * Creates new form ATMS
     */
    public ATMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnBALANCE = new javax.swing.JButton();
        jbtnWITHDRAW = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblDisplay = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtnLOAN = new javax.swing.JButton();
        jbtnDEPOSIT = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jbtnCANCEL = new javax.swing.JButton();
        jbtnCLEAR = new javax.swing.JButton();
        jbtnENTER = new javax.swing.JButton();
        jbtnEXIT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbalance = new javax.swing.JTextField();
        jTxtWithdraw = new javax.swing.JTextField();
        jdeposit = new javax.swing.JTextField();
        jloan = new javax.swing.JTextField();
        jbtnSUBMIT = new javax.swing.JButton();
        jbtnCNCEL = new javax.swing.JButton();
        jbtnRECEIPT = new javax.swing.JButton();
        jbtnBalance = new javax.swing.JButton();
        jbtnWithdraw = new javax.swing.JButton();
        jbtnDeposit = new javax.swing.JButton();
        jbtnLoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnBALANCE.setBackground(new java.awt.Color(51, 153, 0));
        jbtnBALANCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBALANCE.setText("BALANCE");
        jbtnBALANCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBALANCEActionPerformed(evt);
            }
        });

        jbtnWITHDRAW.setBackground(new java.awt.Color(51, 153, 0));
        jbtnWITHDRAW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnWITHDRAW.setText("WITHDRAW");
        jbtnWITHDRAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWITHDRAWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBALANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnWITHDRAW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnBALANCE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtnWITHDRAW)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnLOAN.setBackground(new java.awt.Color(51, 153, 0));
        jbtnLOAN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLOAN.setText("LOAN");
        jbtnLOAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLOANActionPerformed(evt);
            }
        });

        jbtnDEPOSIT.setBackground(new java.awt.Color(51, 153, 0));
        jbtnDEPOSIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDEPOSIT.setText("DEPOSIT");
        jbtnDEPOSIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDEPOSITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnDEPOSIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnLOAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnLOAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDEPOSIT)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jbtnCANCEL.setBackground(new java.awt.Color(255, 0, 0));
        jbtnCANCEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCANCEL.setText("CANCEL");
        jbtnCANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCANCELActionPerformed(evt);
            }
        });

        jbtnCLEAR.setBackground(new java.awt.Color(255, 255, 102));
        jbtnCLEAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCLEAR.setText("CLEAR");
        jbtnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCLEARActionPerformed(evt);
            }
        });

        jbtnENTER.setBackground(new java.awt.Color(0, 153, 51));
        jbtnENTER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnENTER.setText("ENTER");
        jbtnENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnENTERActionPerformed(evt);
            }
        });

        jbtnEXIT.setBackground(new java.awt.Color(102, 102, 255));
        jbtnEXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnEXIT.setText("EXIT");
        jbtnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnCANCEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCLEAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnEXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCLEAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnEXIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("KCB BANK");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextArea1);

        jbalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbalance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtWithdraw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTxtWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWithdrawActionPerformed(evt);
            }
        });

        jdeposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdeposit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jdeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdepositActionPerformed(evt);
            }
        });

        jloan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jloan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnSUBMIT.setBackground(new java.awt.Color(51, 51, 255));
        jbtnSUBMIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSUBMIT.setText("SUBMIT");
        jbtnSUBMIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnSUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSUBMITActionPerformed(evt);
            }
        });

        jbtnCNCEL.setBackground(new java.awt.Color(255, 0, 0));
        jbtnCNCEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCNCEL.setText("CANCEL");
        jbtnCNCEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnCNCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCNCELActionPerformed(evt);
            }
        });

        jbtnRECEIPT.setBackground(new java.awt.Color(0, 255, 255));
        jbtnRECEIPT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnRECEIPT.setText("RECEIPT");
        jbtnRECEIPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnRECEIPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRECEIPTActionPerformed(evt);
            }
        });

        jbtnBalance.setBackground(new java.awt.Color(51, 51, 255));
        jbtnBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBalance.setText("BALANCE");
        jbtnBalance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnWithdraw.setBackground(new java.awt.Color(51, 51, 255));
        jbtnWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnWithdraw.setText("WITHDRAWAL AMMOUNT");
        jbtnWithdraw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnDeposit.setBackground(new java.awt.Color(51, 51, 255));
        jbtnDeposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDeposit.setText("DEPOSIT AMMOUNT");
        jbtnDeposit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnLoan.setBackground(new java.awt.Color(51, 51, 255));
        jbtnLoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLoan.setText("LOAN AMMOUNT");
        jbtnLoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnLoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jTxtWithdraw, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jloan)
                    .addComponent(jdeposit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCNCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnRECEIPT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnBalance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnWithdraw))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnDeposit))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jloan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnLoan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnSUBMIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnRECEIPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCNCEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "1";
        jlblDisplay.setText(Enternumber);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "2";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "3";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "4";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "5";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "6";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "7";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "8";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "9";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "0";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jbtnCANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCANCELActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(this, "are you sure you want to cancel");
    }//GEN-LAST:event_jbtnCANCELActionPerformed

    private void jbtnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCLEARActionPerformed
        // TODO add your handling code here:
        jlblDisplay.setText("");
        jbtnLOAN.setEnabled(false);
        jbtnWITHDRAW.setEnabled(false);
        jbtnDEPOSIT.setEnabled(false);
        jbtnBALANCE.setEnabled(false);
        jbtnEXIT.setEnabled(false);
        jbtnBalance.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
    }//GEN-LAST:event_jbtnCLEARActionPerformed

    private void jbtnENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnENTERActionPerformed
        // TODO add your handling code here:
        int pin1 = Integer.parseInt(jlblDisplay.getText());
        int pin2 = Integer.parseInt(jlblDisplay.getText());
        jlblDisplay.setText("");
        if (pin1 == 1234){
           balance1=50000;
           jbalance.setText(Integer.toString(balance1));
        jbtnLOAN.setEnabled(true);
        jbtnWITHDRAW.setEnabled(true);
        jbtnDEPOSIT.setEnabled(true);
        jbtnBALANCE.setEnabled(true);
        jbtnEXIT.setEnabled(true);
        jbtnBalance.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
        jbtnLoan.setEnabled(false);
        }
        else if (pin2 == 2524){
            balance2=100000;
           jbalance.setText(Integer.toString(balance2));
        jbtnLOAN.setEnabled(true);
        jbtnWITHDRAW.setEnabled(true);
        jbtnDEPOSIT.setEnabled(true);
        jbtnBALANCE.setEnabled(true);
        jbtnEXIT.setEnabled(true);
        jbtnEXIT.setEnabled(true);
        jbtnBalance.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
        jbtnLoan.setEnabled(false);
        }
        else{
            //jlblDisplay.setText("Invalid Pin");
            int balance4 = 10000;
            jbalance.setText(Integer.toString(balance4));
        jbtnLOAN.setEnabled(true);
        jbtnWITHDRAW.setEnabled(true);
        jbtnDEPOSIT.setEnabled(true);
        jbtnBALANCE.setEnabled(true);
        jbtnEXIT.setEnabled(true);
        jbtnBalance.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
        jbtnLoan.setEnabled(false);
        }
    }//GEN-LAST:event_jbtnENTERActionPerformed

    private void jbtnLOANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLOANActionPerformed
        // TODO add your handling code here:
        
        
        jbtnLoan.setEnabled(true);
        jbtnBalance.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
        
    }//GEN-LAST:event_jbtnLOANActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jbtnLOAN.setEnabled(false);
        jbtnWITHDRAW.setEnabled(false);
        jbtnDEPOSIT.setEnabled(false);
        jbtnBALANCE.setEnabled(false);
        jbtnEXIT.setEnabled(false);
       
    }//GEN-LAST:event_formWindowActivated

    private JFrame frame;
    private void jbtnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEXITActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(this,"Do you really want to exit!!");
                System.exit(0);
       
        /*if (JOptionPane.showConfirmDialog(frame, "confirm if you want t exit",
               JOptionPane.YES_NO_OPTION )==JOptionPane.YES_NO_OPTION )
            System.exit(0);8*/
    
       
    }//GEN-LAST:event_jbtnEXITActionPerformed

    private void jbtnBALANCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBALANCEActionPerformed
        // TODO add your handling code here:
        int cbalance = Integer.parseInt(jbalance.getText());
        jlblDisplay.setText(Integer.toString(cbalance));
        
        jbtnBalance.setEnabled(true);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
        jbtnLoan.setEnabled(false);
       
    }//GEN-LAST:event_jbtnBALANCEActionPerformed

    private void jbtnWITHDRAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWITHDRAWActionPerformed
        // TODO add your handling code here:
         jbtnWithdraw.setEnabled(true);
       
       
        
        jbtnBalance.setEnabled(false);
        
        jbtnDeposit.setEnabled(false);
        jbtnLoan.setEnabled(false);
        
       
        
    }//GEN-LAST:event_jbtnWITHDRAWActionPerformed

    private void jbtnDEPOSITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDEPOSITActionPerformed
        // TODO add your handling code here:
        
        
        jbtnDeposit.setEnabled(true);
        jbtnWithdraw.setEnabled(false);
        jbtnBalance.setEnabled(false);
        
        jbtnLoan.setEnabled(false);
    }//GEN-LAST:event_jbtnDEPOSITActionPerformed

    private void jbtnCNCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCNCELActionPerformed
       JOptionPane.showConfirmDialog(this, "are you sure you want to cancel"); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCNCELActionPerformed

    private void jTxtWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWithdrawActionPerformed
       withdrawamount=Integer.parseInt(jTxtWithdraw.getText());
        int balance3 = Integer.parseInt(jbalance.getText());
        
        if(withdrawamount>balance3){
        JOptionPane.showMessageDialog(this,"Sorry you have insufficient funds");
        }
        else{
        jbalance.setText(Integer.toString(balance3-withdrawamount));
        jTxtWithdraw.setText(null);
        }
        
    }//GEN-LAST:event_jTxtWithdrawActionPerformed

    private void jdepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdepositActionPerformed
        // TODO add your handling code here:
        int depositamount = Integer.parseInt(jdeposit.getText());
        int balance = Integer.parseInt(jbalance.getText());
        balance +=depositamount;
        jbalance.setText(Integer.toString(balance));
        jdeposit.setText(null);
    }//GEN-LAST:event_jdepositActionPerformed

    private void jbtnRECEIPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRECEIPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRECEIPTActionPerformed

    private void jbtnSUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSUBMITActionPerformed

        int loan = Integer.parseInt(jloan.getText());
        if(loan<=10000)
        {
        JOptionPane.showMessageDialog(this, "You dont qualify for any loan Amount");
        } else{
        }
    }//GEN-LAST:event_jbtnSUBMITActionPerformed

    private void jbtnLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtWithdraw;
    private javax.swing.JTextField jbalance;
    private javax.swing.JButton jbtnBALANCE;
    private javax.swing.JButton jbtnBalance;
    private javax.swing.JButton jbtnCANCEL;
    private javax.swing.JButton jbtnCLEAR;
    private javax.swing.JButton jbtnCNCEL;
    private javax.swing.JButton jbtnDEPOSIT;
    private javax.swing.JButton jbtnDeposit;
    private javax.swing.JButton jbtnENTER;
    private javax.swing.JButton jbtnEXIT;
    private javax.swing.JButton jbtnLOAN;
    private javax.swing.JButton jbtnLoan;
    private javax.swing.JButton jbtnRECEIPT;
    private javax.swing.JButton jbtnSUBMIT;
    private javax.swing.JButton jbtnWITHDRAW;
    private javax.swing.JButton jbtnWithdraw;
    private javax.swing.JTextField jdeposit;
    private javax.swing.JLabel jlblDisplay;
    private javax.swing.JTextField jloan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       
    }

}

